# Please set environment variables 'QIITA_TOKEN' and 'AUTH_TOKEN_FOR_GITHUBPKG' from your repository
name: Publish articles

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish_articles:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: github.actor != 'actions-user'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "18.14.0"
          registry-url: "https://npm.pkg.github.com"
          scope: "@increments" # for npm private registry
      - run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.AUTH_TOKEN_FOR_GITHUBPKG }} # for npm private registry
      - name: publish article
        run: npm exec qiita publish -- --all
        env:
          QIITA_TOKEN: ${{ secrets.QIITA_TOKEN }}
      - name: commit diff
        run: |
          git add public/*
          if ! git diff --staged --exit-code --quiet
          then
            git config --local user.name "actions-user"
            git config --local user.email "action@github.com"
            git commit -m "Updated by qiita-cli"
            git push
          fi
