name: Publish articles

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish_articles:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      QIITA_TOKEN: ${{ secrets.QIITA_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.14.0"
          registry-url: "https://npm.pkg.github.com"
          scope: "@increments" # for npm private registry
      - run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.AUTH_TOKEN_FOR_GITHUBPKG }} # for npm private registry
      - name: publish articles
        run: |
          find ./public -name *.md -not -path "./public/remote/*" | xargs basename -s .md
      # - name: commit diffs
      #   run: find ./tmp -name '*.md' -not -path "${QIITA_CLI_ITEMS_ROOT}/public/remote/*.md"
