name: Sync remote and create PR

on:
  schedule:
    - cron: '0 22 * * *' # 7:00 JST
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sync_remote_and_create_pr:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: master
      - uses: ./.github/actions/setup-dependencies
      - run: pnpm exec qiita pull -- --force
        env:
          QIITA_TOKEN: ${{ secrets.QIITA_TOKEN }}
      - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          commit-message: 'Sync article files'
          delete-branch: true
          title: 'Sync article files'
          reviewers: fussy113
